services:
  client_0:
    build: { context: ./src/, dockerfile: client/Dockerfile }
    depends_on:
      rabbitmq: { condition: service_healthy }
      gateway_1: { condition: service_started }
      filter_period1: { condition: service_started }
      filter_wire_ach: { condition: service_started }
      filter_currency_usd_p1: { condition: service_started }
      filter_period2: { condition: service_started }
      filter_currency_usd_p2: { condition: service_started }
      filter_currency_usd_other_periods: { condition: service_started }
      joiner_usd: { condition: service_started }
      filter_amount_lt_50: { condition: service_started }
      drain_q1_input: { condition: service_started }
      drain_period1_wire_ach: { condition: service_started }
      sharder_q4: { condition: service_started }
      path_finder_q4: { condition: service_started }
      counter_q4: { condition: service_started }
      drain_q4: { condition: service_started }
      drain_period2_usd: { condition: service_started }
      drain_usd_joined: { condition: service_started }
    env_file:
      - .env
    environment:
      - INPUT_TRANSACTIONS=/datasets/LI-Small_Trans.csv
      - INPUT_ACCOUNTS=/datasets/LI-Small_accounts.csv
      - GATEWAY_PREFIX=gateway_
      - GATEWAY_AMOUNT=1
      - GATEWAY_PORT=5678
      - CONNECT_MAX_ATTEMPTS=6
      - CONNECT_TIMEOUT_MS=800
      - BACKOFF_BASE_MS=200
      - BACKOFF_MAX_MS=3000
      - RESULTS_DIR=/results
      - LOG_LEVEL=info
    volumes:
      - ./datasets:/datasets
      - ./results/client_0:/results
  gateway_1:
    build: { context: ./src/, dockerfile: gateway/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - ALL_TRANSACTIONS_QUEUE=all_transactions
      - ALL_ACCOUNTS_QUEUE=all_accounts
      - FINAL_QUEUE=final
      - GATEWAY_ID=1
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5678
      - LOG_LEVEL=info
  filter_period1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period1
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:all_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=direct_exchange:period1_transactions
      - OUTPUT_1=queue:non_period1_transactions
      - LOG_LEVEL=info
  filter_wire_ach:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_wire_ach
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:period1_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period1_wire_ach
      - LOG_LEVEL=info
  filter_currency_usd_p1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p1
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:period1_transactions
      - OUTPUTS_MATCH_COUNT=2
      - OUTPUT_0=queue:period1_usd_for_drain
      - OUTPUT_1=sharded_queues:joiner_usd_input:1
      - LOG_LEVEL=info
  filter_period2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period2
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:non_period1_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period2_transactions
      - OUTPUT_1=queue:other_dates_transactions
      - LOG_LEVEL=info
  filter_currency_usd_p2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p2
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:period2_transactions
      - OUTPUTS_MATCH_COUNT=2
      - OUTPUT_0=direct_exchange:period2_usd_direct_exchange
      - OUTPUT_1=sharded_queues:joiner_usd_input:1
      - LOG_LEVEL=info
  filter_currency_usd_other_periods:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_other_periods
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:other_dates_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=sharded_queues:joiner_usd_input:1
      - LOG_LEVEL=info
  joiner_usd:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=joiner_usd
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:joiner_usd_input_0
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:usd
      - LOG_LEVEL=info
      - EXPECTED_EOFS=3
  filter_amount_lt_50:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_amount_lt_50
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:usd
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q1_input
      - LOG_LEVEL=info
  drain_q1_input:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=drain
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:q1_input
      - OUTPUTS_MATCH_COUNT=0
      - LOG_LEVEL=info
      - DRAIN_OUTPUT_FILE=/results/drain_q1_input.csv
    volumes:
      - ./results:/results
  drain_period1_wire_ach:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=drain
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:period1_wire_ach
      - OUTPUTS_MATCH_COUNT=0
      - LOG_LEVEL=info
      - DRAIN_OUTPUT_FILE=/results/drain_period1_wire_ach.csv
    volumes:
      - ./results:/results
  sharder_q4:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=sharder_q4
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:period1_usd_for_drain
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:q4_account_shards
      - LOG_LEVEL=info
      - K_PATH_FINDERS=1
  path_finder_q4:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=path_finder_q4
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:q4_account_shards:0
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:q4_pair_shards
      - LOG_LEVEL=info
      - K_COUNTERS=1
      - N_SHARDERS=1
  counter_q4:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=counter_q4
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:q4_pair_shards:0
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:results
      - LOG_LEVEL=info
      - MIN_INTERMEDIATES=5
      - N_FINAL_JOINERS=1
      - N_PATH_FINDERS=1
  drain_q4:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=drain_q4
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:results:0
      - OUTPUTS_MATCH_COUNT=0
      - LOG_LEVEL=info
      - DRAIN_OUTPUT_FILE=/results/drain_q4.csv
    volumes:
      - ./results:/results
  drain_period2_usd:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=drain
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:period2_usd_direct_exchange
      - OUTPUTS_MATCH_COUNT=0
      - LOG_LEVEL=info
      - DRAIN_OUTPUT_FILE=/results/drain_period2_usd.csv
    volumes:
      - ./results:/results
  drain_usd_joined:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=drain
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:usd
      - OUTPUTS_MATCH_COUNT=0
      - LOG_LEVEL=info
      - DRAIN_OUTPUT_FILE=/results/drain_usd_joined.csv
    volumes:
      - ./results:/results
  rabbitmq:
    build: { context: ./src/rabbitmq, dockerfile: Dockerfile }
    volumes:
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - 5672:5672
      - 15672:15672
