services:
  client_0:
    build: { context: ./src/, dockerfile: client/Dockerfile }
    depends_on:
      rabbitmq: { condition: service_healthy }
      gateway_1: { condition: service_started }
      gateway_2: { condition: service_started }
      filter_period1_0: { condition: service_started }
      filter_period1_1: { condition: service_started }
      filter_period1_2: { condition: service_started }
      filter_currency_usd_p1_0: { condition: service_started }
      filter_currency_usd_p1_1: { condition: service_started }
      filter_currency_usd_p1_2: { condition: service_started }
      filter_period2_0: { condition: service_started }
      filter_period2_1: { condition: service_started }
      filter_period2_2: { condition: service_started }
      filter_currency_usd_p2_0: { condition: service_started }
      filter_currency_usd_p2_1: { condition: service_started }
      filter_currency_usd_p2_2: { condition: service_started }
      average_local_q3_0: { condition: service_started }
      average_local_q3_1: { condition: service_started }
      average_local_q3_2: { condition: service_started }
      average_global_q3: { condition: service_started }
      filter_q3: { condition: service_started }
      final_joiner_0: { condition: service_started }
      final_joiner_1: { condition: service_started }
    env_file:
      - .env
    environment:
      - INPUT_TRANSACTIONS=/datasets/LI-Small_Trans.csv
      - INPUT_ACCOUNTS=/datasets/LI-Small_accounts.csv
      - GATEWAY_PREFIX=gateway_
      - GATEWAY_AMOUNT=2
      - GATEWAY_PORT=5678
      - CONNECT_MAX_ATTEMPTS=6
      - CONNECT_TIMEOUT_MS=800
      - BACKOFF_BASE_MS=200
      - BACKOFF_MAX_MS=3000
      - RESULTS_DIR=/results
      - EXPECTED_QUERY_EOFS=1
      - LOG_LEVEL=info
    volumes:
      - ./datasets:/datasets
      - ./results/client_0:/results
  client_1:
    build: { context: ./src/, dockerfile: client/Dockerfile }
    depends_on:
      rabbitmq: { condition: service_healthy }
      gateway_1: { condition: service_started }
      gateway_2: { condition: service_started }
      filter_period1_0: { condition: service_started }
      filter_period1_1: { condition: service_started }
      filter_period1_2: { condition: service_started }
      filter_currency_usd_p1_0: { condition: service_started }
      filter_currency_usd_p1_1: { condition: service_started }
      filter_currency_usd_p1_2: { condition: service_started }
      filter_period2_0: { condition: service_started }
      filter_period2_1: { condition: service_started }
      filter_period2_2: { condition: service_started }
      filter_currency_usd_p2_0: { condition: service_started }
      filter_currency_usd_p2_1: { condition: service_started }
      filter_currency_usd_p2_2: { condition: service_started }
      average_local_q3_0: { condition: service_started }
      average_local_q3_1: { condition: service_started }
      average_local_q3_2: { condition: service_started }
      average_global_q3: { condition: service_started }
      filter_q3: { condition: service_started }
      final_joiner_0: { condition: service_started }
      final_joiner_1: { condition: service_started }
    env_file:
      - .env
    environment:
      - INPUT_TRANSACTIONS=/datasets/LI-Small_Trans.csv
      - INPUT_ACCOUNTS=/datasets/LI-Small_accounts.csv
      - GATEWAY_PREFIX=gateway_
      - GATEWAY_AMOUNT=2
      - GATEWAY_PORT=5678
      - CONNECT_MAX_ATTEMPTS=6
      - CONNECT_TIMEOUT_MS=800
      - BACKOFF_BASE_MS=200
      - BACKOFF_MAX_MS=3000
      - RESULTS_DIR=/results
      - EXPECTED_QUERY_EOFS=1
      - LOG_LEVEL=info
    volumes:
      - ./datasets:/datasets
      - ./results/client_1:/results
  gateway_1:
    build: { context: ./src/, dockerfile: gateway/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - ALL_TRANSACTIONS_QUEUE=all_transactions
      - ALL_ACCOUNTS_QUEUE=all_accounts
      - FINAL_QUEUE=final
      - GATEWAY_ID=1
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5678
      - EXPECTED_QUERY_EOFS=1
      - LOG_LEVEL=info
  gateway_2:
    build: { context: ./src/, dockerfile: gateway/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - ALL_TRANSACTIONS_QUEUE=all_transactions
      - ALL_ACCOUNTS_QUEUE=all_accounts
      - FINAL_QUEUE=final
      - GATEWAY_ID=2
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5678
      - EXPECTED_QUERY_EOFS=1
      - LOG_LEVEL=info
  filter_period1_0:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period1
      - REPLICA_ID=0
      - N_REPLICAS=3
      - INPUT=queue:all_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period1_for_currency_usd_p1
      - OUTPUT_1=queue:non_period1_transactions
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_period1_0
      - RING_QUEUE_OUT=ring_filter_period1_1
  filter_period1_1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period1
      - REPLICA_ID=1
      - N_REPLICAS=3
      - INPUT=queue:all_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period1_for_currency_usd_p1
      - OUTPUT_1=queue:non_period1_transactions
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_period1_1
      - RING_QUEUE_OUT=ring_filter_period1_2
  filter_period1_2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period1
      - REPLICA_ID=2
      - N_REPLICAS=3
      - INPUT=queue:all_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period1_for_currency_usd_p1
      - OUTPUT_1=queue:non_period1_transactions
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_period1_2
      - RING_QUEUE_OUT=ring_filter_period1_0
  filter_currency_usd_p1_0:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p1
      - REPLICA_ID=0
      - N_REPLICAS=3
      - INPUT=queue:period1_for_currency_usd_p1
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q3_p1_usd
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_currency_usd_p1_0
      - RING_QUEUE_OUT=ring_filter_currency_usd_p1_1
  filter_currency_usd_p1_1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p1
      - REPLICA_ID=1
      - N_REPLICAS=3
      - INPUT=queue:period1_for_currency_usd_p1
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q3_p1_usd
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_currency_usd_p1_1
      - RING_QUEUE_OUT=ring_filter_currency_usd_p1_2
  filter_currency_usd_p1_2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p1
      - REPLICA_ID=2
      - N_REPLICAS=3
      - INPUT=queue:period1_for_currency_usd_p1
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q3_p1_usd
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_currency_usd_p1_2
      - RING_QUEUE_OUT=ring_filter_currency_usd_p1_0
  filter_period2_0:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period2
      - REPLICA_ID=0
      - N_REPLICAS=3
      - INPUT=queue:non_period1_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period2_transactions
      - OUTPUT_1=queue:other_dates_transactions
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_period2_0
      - RING_QUEUE_OUT=ring_filter_period2_1
  filter_period2_1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period2
      - REPLICA_ID=1
      - N_REPLICAS=3
      - INPUT=queue:non_period1_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period2_transactions
      - OUTPUT_1=queue:other_dates_transactions
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_period2_1
      - RING_QUEUE_OUT=ring_filter_period2_2
  filter_period2_2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_period2
      - REPLICA_ID=2
      - N_REPLICAS=3
      - INPUT=queue:non_period1_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:period2_transactions
      - OUTPUT_1=queue:other_dates_transactions
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_period2_2
      - RING_QUEUE_OUT=ring_filter_period2_0
  filter_currency_usd_p2_0:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p2
      - REPLICA_ID=0
      - N_REPLICAS=3
      - INPUT=queue:period2_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q3_filter_input
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_currency_usd_p2_0
      - RING_QUEUE_OUT=ring_filter_currency_usd_p2_1
  filter_currency_usd_p2_1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p2
      - REPLICA_ID=1
      - N_REPLICAS=3
      - INPUT=queue:period2_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q3_filter_input
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_currency_usd_p2_1
      - RING_QUEUE_OUT=ring_filter_currency_usd_p2_2
  filter_currency_usd_p2_2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_currency_usd_p2
      - REPLICA_ID=2
      - N_REPLICAS=3
      - INPUT=queue:period2_transactions
      - OUTPUTS_MATCH_COUNT=1
      - OUTPUT_0=queue:q3_filter_input
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_filter_currency_usd_p2_2
      - RING_QUEUE_OUT=ring_filter_currency_usd_p2_0
  average_local_q3_0:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=average_local_q3
      - REPLICA_ID=0
      - N_REPLICAS=3
      - INPUT=queue:q3_p1_usd
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:q3_avg_global_input
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_average_local_q3_0
      - RING_QUEUE_OUT=ring_average_local_q3_1
      - K_AGGREGATORS_Q3=1
  average_local_q3_1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=average_local_q3
      - REPLICA_ID=1
      - N_REPLICAS=3
      - INPUT=queue:q3_p1_usd
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:q3_avg_global_input
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_average_local_q3_1
      - RING_QUEUE_OUT=ring_average_local_q3_2
      - K_AGGREGATORS_Q3=1
  average_local_q3_2:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=average_local_q3
      - REPLICA_ID=2
      - N_REPLICAS=3
      - INPUT=queue:q3_p1_usd
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:q3_avg_global_input
      - LOG_LEVEL=info
      - RING_QUEUE_IN=ring_average_local_q3_2
      - RING_QUEUE_OUT=ring_average_local_q3_0
      - K_AGGREGATORS_Q3=1
  average_global_q3:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=average_global_q3
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=direct_exchange:q3_avg_global_input:0
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=queue:q3_filter_input
      - LOG_LEVEL=info
      - EXPECTED_PARTIAL_EOFS=3
      - N_FILTER_Q3=1
  filter_q3:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=filter_q3
      - REPLICA_ID=0
      - N_REPLICAS=1
      - INPUT=queue:q3_filter_input
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=direct_exchange:results
      - LOG_LEVEL=info
      - BUFFER_DIR=/tmp
      - EXPECTED_PARTIAL_EOFS=2
      - N_FINAL_JOINERS=2
  final_joiner_0:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=final_joiner
      - REPLICA_ID=0
      - N_REPLICAS=2
      - INPUT=direct_exchange:results:0
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=final_queue:final_1
      - OUTPUT_1=final_queue:final_2
      - LOG_LEVEL=info
      - EXPECTED_EOFS_Q3=1
  final_joiner_1:
    build: { context: ./src/, dockerfile: worker/Dockerfile }
    depends_on: { rabbitmq: { condition: service_healthy } }
    env_file:
      - .env
    environment:
      - STRATEGY=final_joiner
      - REPLICA_ID=1
      - N_REPLICAS=2
      - INPUT=direct_exchange:results:1
      - OUTPUTS_MATCH_COUNT=0
      - OUTPUT_0=final_queue:final_1
      - OUTPUT_1=final_queue:final_2
      - LOG_LEVEL=info
      - EXPECTED_EOFS_Q3=1
  rabbitmq:
    build: { context: ./src/rabbitmq, dockerfile: Dockerfile }
    volumes:
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - 5672:5672
      - 15672:15672
